# Generated by Django 5.2 on 2025-04-30 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.IntegerField(max_length=8)),
                ('dv', models.CharField(max_length=1)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('rut_empresa', models.IntegerField(max_length=20)),
                ('puntuacion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Proveedor',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regprovs.marca')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regprovs.proveedor')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regprovs.tipo')),
            ],
        ),
    ]
