# Generated by Django 5.2 on 2025-04-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regprovs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='rut',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rut_empresa',
            field=models.IntegerField(),
        ),
    ]
