# Generated by Django 5.2 on 2025-05-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regprovs', '0002_alter_proveedor_rut_alter_proveedor_rut_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_proveedor',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
