# Generated by Django 5.2 on 2025-05-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regprovs', '0004_proveedor_correo_proveedor_pais_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rol', models.CharField(max_length=1)),
                ('idproveedor', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
