name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.EC2_SSH_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Connect to EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.EC2_PORT || 22 }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
          cd /home/ec2-user/ApiRegProv || (git clone https://github.com/be-camacho/ApiRegProv /home/ec2-user/ApiRegProv && cd /home/ec2-user/ApiRegProv)
          git pull origin main
          sudo docker stop $(sudo docker ps -q --filter ancestor=apiprovs) || true
          sudo docker rm $(sudo docker ps -aq --filter ancestor=apiprovs) || true
          sudo docker build -t apiprovs .
          sudo docker run -d -p 80:8000 apiprovs
        "
