name: Deploy to EC2
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # ... otros pasos previos

      - name: Connect to EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no \
              -p "${{ secrets.EC2_PORT || 22 }}" \
              "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}" \
              /bin/bash << 'EOSSH'
              # Comandos dentro del servidor
              cd /home/ec2-user/ApiRegProv
              git pull origin main

              # Crear .env
              cat > .env << EOF
              DB_NAME=${{ secrets.DB_NAME }}
              DB_USER=${{ secrets.DB_USER }}
              DB_PASSWORD=${{ secrets.DB_PASSWORD }}
              DB_HOST=${{ secrets.DB_HOST }}
              DB_PORT=${{ secrets.DB_PORT }}
              EOF
              chmod 600 .env
              # ... resto de comandos
EOSSH
        env:  # ✅ Bloque CORRECTO (fuera del 'run'!)
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}