name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.EC2_SSH_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Connect to EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.EC2_PORT || 22 }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
          cd /home/ec2-user/ApiRegProv || (git clone https://github.com/be-camacho/ApiRegProv.git /home/ec2-user/ApiRegProv && cd /home/ec2-user/ApiRegProv)
          git pull origin main
          
          # 1. Detener y eliminar todos los contenedores relacionados
          sudo docker ps -a -q --filter ancestor=apiprovs | xargs -r sudo docker stop | xargs -r sudo docker rm
          
          # 2. Liberar el puerto 80 de cualquier proceso
          sudo fuser -k 80/tcp || true
          
          # 3. Limpiar recursos de Docker no utilizados
          sudo docker system prune -f
          
          # 4. Reconstruir la imagen
          sudo docker build -t apiprovs .
          
          # 5. Ejecutar el contenedor con reinicio automático
          sudo docker run -d \
            --restart unless-stopped \
            -p 80:8000 \
            --name apiprovs_container \
            apiprovs
        "
