name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.EC2_SSH_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Connect to EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.EC2_PORT || 22 }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
          # 1. Actualizar código
          cd /home/ec2-user/ApiRegProv
          git pull origin main
          
          # 2. Detener y eliminar contenedores existentes
          sudo docker ps -aq --filter name=apiprovs_container | xargs -r sudo docker stop | xargs -r sudo docker rm
          
          # 3. Liberar puerto 80 completamente
          sudo lsof -ti :80 | xargs -r sudo kill -9
          sudo ss -tulnp | grep ':80' | awk '{print $7}' | cut -d\"=\" -f2 | xargs -r sudo kill -9
          
          # 4. Limpiar redes Docker huérfanas
          sudo docker network prune -f
          
          # 5. Reconstruir imagen
          sudo docker build -t apiprovs .
          
          # 6. Ejecutar con política de reinicio y nombre específico
          sudo docker run -d \
            --name apiprovs_container \
            --restart unless-stopped \
            -p 80:8000 \
            -v /etc/ssl:/etc/ssl \
            apiprovs
          
          # 7. Verificar despliegue
          sleep 10
          sudo docker ps
          curl -I http://localhost:80
        "
